migrations:
	python manage.py makemigrations

migrate:
	python manage.py migrate

testing:
	python -m pytest

start_db:
	docker start cryptoPSQL

stop_db:
	docker stop cryptoPSQL

start_redis:
	docker start redis

stop_redis:
	docker stop redis

