# Generated by Django 5.1.2 on 2024-10-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txHash", models.CharField(max_length=66, unique=True)),
                ("senderAddress", models.CharField(max_length=42)),
                ("recipientAddress", models.CharField(max_length=42)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
