# Generated by Django 5.1.2 on 2024-10-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="transaction",
            table="transactions",
        ),
    ]
