# Generated by Django 5.1.2 on 2024-10-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transaction_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="recipientAddress",
            new_name="recipient_address",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="senderAddress",
            new_name="sender_address",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="txHash",
            new_name="tx_hash",
        ),
    ]
